// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js reads .env.local, but the Prisma CLI only auto-loads .env. Load both
// (local first, without overriding real shell env) so migrations find the URL.
config({ path: [".env.local", ".env"] });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection; fall back to the
    // pooled URL for local/dev where only one is set.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
